"""
api/services/users_db.py

Supabase DB operations for the `users` table.

The `id` column is a UUID generated by Supabase (gen_random_uuid()).
Python never creates a user ID — it always comes back from the DB.

Graceful fallback: if Supabase is not configured, returns None and the
caller falls back to the existing in-memory UUID approach.

Run once in Supabase SQL Editor to create the table:
──────────────────────────────────────────────────────────────────────
  create table if not exists users (
    id             uuid primary key default gen_random_uuid(),
    google_id      text not null unique,
    email          text not null,
    name           text not null,
    avatar_url     text,
    phone_number   text,
    created_at     timestamptz not null default now(),
    last_login_at  timestamptz not null default now()
  );
  create unique index if not exists users_google_id_idx on users(google_id);
  create unique index if not exists users_email_idx    on users(email);
──────────────────────────────────────────────────────────────────────
"""
from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)

_TABLE = "users"


def _client():
    url = os.environ.get("SUPABASE_URL", "")
    key = os.environ.get("SUPABASE_SERVICE_KEY", "")
    if not (url and key):
        return None
    try:
        from supabase import create_client
        return create_client(url, key)
    except Exception as exc:
        logger.warning("Supabase client init failed: %s", exc)
        return None


def upsert_user(
    google_id: str,
    email: str,
    name: str,
    avatar_url: Optional[str] = None,
) -> Optional[dict]:
    """
    Insert or update a user row keyed on google_id.
    On conflict (returning user) refreshes email, name, avatar_url, last_login_at.
    Returns the full row dict (including the DB-generated `id`) or None on failure.
    """
    sb = _client()
    if sb is None:
        return None

    now_iso = datetime.now(timezone.utc).isoformat()
    try:
        resp = (
            sb.table(_TABLE)
            .upsert(
                {
                    "google_id": google_id,
                    "email": email,
                    "name": name,
                    "avatar_url": avatar_url,
                    "last_login_at": now_iso,
                },
                on_conflict="google_id",
            )
            .execute()
        )
        rows = resp.data or []
        if not rows:
            logger.error("upsert_user returned no rows for google_id=%s", google_id)
            return None
        return rows[0]
    except Exception as exc:
        logger.error("upsert_user failed for google_id=%s: %s", google_id, exc)
        return None


def get_user_by_id(user_id: str) -> Optional[dict]:
    """Fetch a user row by platform UUID. Returns dict or None."""
    sb = _client()
    if sb is None:
        return None
    try:
        resp = sb.table(_TABLE).select("*").eq("id", user_id).single().execute()
        return resp.data
    except Exception as exc:
        logger.error("get_user_by_id failed for id=%s: %s", user_id, exc)
        return None
