from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from pydantic import BaseModel


class User(BaseModel):
    id: str                              # UUID generated by Supabase (never by Python)
    google_id: str
    email: str
    name: str
    avatar_url: Optional[str] = None
    phone_number: Optional[str] = None  # Not returned by Google basic profile; updatable later
    created_at: Optional[datetime] = None
    last_login_at: Optional[datetime] = None


# ── In-memory session cache ───────────────────────────────────────────────────
# Populated on every login. Used for fast JWT validation without a DB round-trip.
_by_id: dict[str, User] = {}
_by_google_id: dict[str, User] = {}


def _cache(user: User) -> User:
    _by_id[user.id] = user
    _by_google_id[user.google_id] = user
    return user


def _row_to_user(row: dict) -> User:
    return User(
        id=str(row["id"]),
        google_id=row["google_id"],
        email=row["email"],
        name=row["name"],
        avatar_url=row.get("avatar_url"),
        phone_number=row.get("phone_number"),
        created_at=datetime.fromisoformat(row["created_at"]) if row.get("created_at") else None,
        last_login_at=datetime.fromisoformat(row["last_login_at"]) if row.get("last_login_at") else None,
    )


# ── Public API ────────────────────────────────────────────────────────────────


def get_or_create_user(
    google_id: str,
    email: str,
    name: str,
    avatar_url: Optional[str] = None,
) -> User:
    """
    Upsert user via Supabase DB (ID generated by DB).
    Falls back to in-memory UUID if Supabase is not configured.
    Result is always cached in memory for the lifetime of the process.
    """
    from api.services import users_db

    row = users_db.upsert_user(google_id=google_id, email=email, name=name, avatar_url=avatar_url)
    if row:
        return _cache(_row_to_user(row))

    # ── Fallback: Supabase not configured — use in-memory store ──────────────
    if google_id in _by_google_id:
        existing = _by_google_id[google_id]
        return _cache(existing.model_copy(update={"email": email, "name": name, "avatar_url": avatar_url}))

    user = User(
        id=str(uuid.uuid4()),
        google_id=google_id,
        email=email,
        name=name,
        avatar_url=avatar_url,
    )
    return _cache(user)


def get_user_by_id(user_id: str) -> Optional[User]:
    """
    Check memory cache first (O(1)).
    On miss, query Supabase (covers server restarts / new workers).
    """
    if user_id in _by_id:
        return _by_id[user_id]

    from api.services import users_db

    row = users_db.get_user_by_id(user_id)
    if row:
        return _cache(_row_to_user(row))

    return None
